<a href="https://colab.research.google.com/github/chadboii/Math-Workshop-/blob/main/Math_WorkShop_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1: Create a 2D ndarray of type Integer, e.g., �
1 2 3
4 5 6
7 8 9
� and see its properties.

In [1]:
import numpy as np

if __name__ == "__main__":

  arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
  print("Array = ")
  print(arr)
  print("Data Type of the Array          =", arr.dtype)
  print("Number of dimensions of the Array          =", arr.ndim)
  print("Shape of the Array           =", arr.shape)
  print("Size of the Array           =", arr.size)
  print("Number of bytes used by each element of the Array          =", arr.itemsize)
  print("Total bytes used by the Array         =", arr.nbytes)
  print("Memory Layout information        =", arr.flags)




Array = 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Data Type of the Array          = float64
Number of dimensions of the Array          = 2
Shape of the Array           = (3, 3)
Size of the Array           = 9
Number of bytes used by each element of the Array          = 8
Total bytes used by the Array         = 72
Memory Layout information        =   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



Problem 2: Create a 2D ndarray (matrix) of shape (4,5) with all elements equal to 3.0 and print
the matrix.

In [3]:
arr2 = 3 * np.ones((4,5),dtype=float)
print("Array = ")
print(arr2)
print("Shape =", arr2.shape)
print("Datatype= ", arr2.dtype)

Array = 
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape = (4, 5)
Datatype=  float64


Problem 3: What is the other way to create the same matrix as above?


In [4]:
arr4 = np.fromfunction(lambda i, j: np.abs(i+1-3*(j+1))/2, (3,3), dtype=int)
print("Array = ")
print(arr4)
print("Shape =", arr4.shape)
print("Datatype= ", arr4.dtype)

Array = 
[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape = (3, 3)
Datatype=  float64


PART 2
Problem 2: Given a matrix and a vector, write a Python function that performs Matrix-Vector
product. Check your result with NumPy built-in function to perform Matrix-Vector/MatrixMatrix product.

In [11]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [1, 1, 1],
    [2, 2, 2]
])

print(A + B)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [9]:
def dot_product(vec1, vec2):

  vec1 = vec1.flatten()
  vec2 = vec2.flatten()
  return np.sum(np.multiply(vec1, vec2))

def matrix_vector_product(at, vec):
  m,n = mat.shape
  p,q = vec.Shape

  assert n == p,

  result = np.zeros((m,q),dtype=float)


  for i in range(m)
     result[i] = dot_product(mat[i,:], vec)

  return result

SyntaxError: invalid syntax (1508954010.py, line 11)

In [10]:
mat1 = np.full((3,3), 3, dtype=int)
vec1 = np.full((3,1), 2, dtype=int)
print("Matrix = ")
print(mat1)
print("Vector = ")
print(vec1)

result1 = matrix_vector_product(mat1, vec1)
print("Result = ")
print(result1)

result2 = mat1 @ vec1
print("Result = ")
print(result2)

Matrix = 
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector = 
[[2]
 [2]
 [2]]


NameError: name 'matrix_vector_product' is not defined

In [12]:
def matrix_matrix_product(matrix1, matrix2):
    matrix1 = np.asarray(matrix1)
    matrix2 = np.asarray(matrix2)

    rows1, columns1 = matrix1.shape
    rows2, columns2 = matrix2.shape

    if columns1 != rows2:
        raise ValueError("Matrices are not compatible for multiplication.")

    result = np.zeros((rows1, columns2), dtype=float)

    for i in range(rows1):
        for j in range(columns2):
            result[i, j] = dot_product(
                matrix1[i, :],
                matrix2[:, j]
            )

    return result


A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

manual_result = matrix_matrix_product(A, B)
numpy_result = A @ B

print("Matrix A =")
print(A)

print("Matrix B =")
print(B)

print("Manual Result =")
print(manual_result)

print("NumPy Result =")
print(numpy_result)

NameError: name 'dot_product' is not defined

In [13]:
def is_symmetric(matrix):
    matrix = np.asarray(matrix)

    # A symmetric matrix must be square
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        return False

    return np.allclose(matrix, matrix.T)


matrix1 = np.array([
    [1, 2, 3],
    [2, 4, 5],
    [3, 5, 6]
])

matrix2 = np.array([
    [1, 2],
    [3, 4]
])

print("Matrix 1 is symmetric:", is_symmetric(matrix1))
print("Matrix 2 is symmetric:", is_symmetric(matrix2))

Matrix 1 is symmetric: True
Matrix 2 is symmetric: False
